---
swagger: "2.0"
info:
  description: Genearte swagger to create artifacts for Services API
  version: 1.0.0
  title: Services API
host: virtserver.swaggerhub.com
basePath: /reddy78/services/1.0.0
tags:
- name: Service
  description: Detail service Info.
schemes:
- https
produces:
- application/json
paths:
  /service:
    get:
      tags:
      - Service
      summary: Get all services
      description: Return all services
      operationId: getServices
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Service'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ApiResponse'
        404:
          description: Service not found
          schema:
            $ref: '#/definitions/ApiResponse'
        500:
          description: Service unaviable
          schema:
            $ref: '#/definitions/ApiResponse'
  /service/{plan}:
    get:
      tags:
      - Service
      summary: Get service details by plan
      description: Return a single service
      operationId: getServiceByPlan
      produces:
      - application/json
      parameters:
      - name: plan
        in: path
        description: ID of Service  to return
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Service'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ApiResponse'
        404:
          description: Service not found
          schema:
            $ref: '#/definitions/ApiResponse'
        500:
          description: Service unaviable
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  Service:
    type: object
    properties:
      Plan:
        type: string
      Price:
        type: number
        format: float
      Text:
        type: string
      Voice:
        type: string
      Data:
        type: string
      AddOn:
        type: string
    description: Model contains service Plan, Price,Text,Voice,Data and AddOns
    example:
      Price: 0.8008282
      Plan: Basic
      Text: Unlimited
      Voice: Unlimited
      Data: 5GB
      AddOn: Hulu
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
